const labels = [
    "persona",
    "bicicleta",
    "automóvil",
    "motocicleta",
    "avión",
    "autobús",
    "tren",
    "camión",
    "barco",
    "semáforo",
    "hidrante",
    "señal de alto",
    "parquímetro",
    "banco",
    "pájaro",
    "gato",
    "perro",
    "caballo",
    "oveja",
    "vaca",
    "elefante",
    "oso",
    "cebra",
    "jirafa",
    "mochila",
    "paraguas",
    "bolso",
    "corbata",
    "valija",
    "frisbee",
    "esquí",
    "snowboard",
    "pelota deportiva",
    "barrilete",
    "bate de béisbol",
    "guante de béisbol",
    "skate",
    "tabla de surf",
    "raqueta de tenis",
    "botella",
    "copa de vino",
    "taza",
    "tenedor",
    "cuchillo",
    "cuchara",
    "bol",
    "banana",
    "manzana",
    "sándwich",
    "naranja",
    "brócoli",
    "zanahoria",
    "pancho",
    "pizza",
    "dona",
    "torta",
    "silla",
    "sofá",
    "planta en maceta",
    "cama",
    "mesa de comedor",
    "inodoro",
    "televisor",
    "notebook",
    "mouse",
    "control remoto",
    "teclado",
    "teléfono celular",
    "microondas",
    "horno",
    "tostadora",
    "pileta",
    "heladera",
    "libro",
    "reloj",
    "jarrón",
    "tijera",
    "oso de peluche",
    "secador de pelo",
    "cepillo de dientes"
];
